version: '3.9'
services:
  db:
    image: 'surrealdb/surrealdb:latest'
    environment:
      - SURREAL_DATABASE=/data/db
      - SURREAL_PASSWORD=password
    volumes:
      - 'surreal_data:/data/db'
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:80'
    depends_on:
      - db
    environment:
      - ConnectionStrings:DefaultConnection=SurrealDBServer=db;SurrealDBPort=5432;SurrealDBUser=surreal;SurrealDBPassword=password;SurrealDBDatabase=HajurKoCarRental;SurrealDBNamespace=my-namespace
volumes:
  surreal_data:
